param(
    [string]$ContentRoot = "content",
    [string]$OutputPath = "src/ReplicatedStorage/CivilizationWar/Shared/GeneratedContent.lua"
)

$ErrorActionPreference = "Stop"

function Escape-LuauString {
    param([string]$Value)

    $escaped = $Value.Replace("\", "\\").Replace("`r", "\r").Replace("`n", "\n").Replace('"', '\"')
    return '"' + $escaped + '"'
}

function Get-LuauKey {
    param([string]$Key)

    if ($Key -match "^[A-Za-z_][A-Za-z0-9_]*$") {
        return $Key
    }

    return "[" + (Escape-LuauString $Key) + "]"
}

function ConvertTo-LuauValue {
    param(
        [AllowNull()]$Value,
        [int]$Indent = 0
    )

    $pad = " " * $Indent
    $childPad = " " * ($Indent + 4)

    if ($null -eq $Value) {
        return "nil"
    }

    if ($Value -is [string]) {
        return Escape-LuauString $Value
    }

    if ($Value -is [bool]) {
        if ($Value) { return "true" }
        return "false"
    }

    if ($Value -is [byte] -or $Value -is [sbyte] -or $Value -is [int16] -or $Value -is [uint16] -or $Value -is [int] -or $Value -is [uint32] -or $Value -is [long] -or $Value -is [uint64] -or $Value -is [single] -or $Value -is [double] -or $Value -is [decimal]) {
        return [System.Convert]::ToString($Value, [System.Globalization.CultureInfo]::InvariantCulture)
    }

    if ($Value -is [System.Management.Automation.PSCustomObject]) {
        $lines = @("{")
        foreach ($property in $Value.PSObject.Properties) {
            $key = Get-LuauKey $property.Name
            $converted = ConvertTo-LuauValue $property.Value ($Indent + 4)
            $lines += "$childPad$key = $converted,"
        }
        $lines += "$pad}"
        return ($lines -join "`n")
    }

    if ($Value -is [System.Collections.IDictionary]) {
        $lines = @("{")
        foreach ($keyObject in $Value.Keys) {
            $key = Get-LuauKey ([string]$keyObject)
            $converted = ConvertTo-LuauValue $Value[$keyObject] ($Indent + 4)
            $lines += "$childPad$key = $converted,"
        }
        $lines += "$pad}"
        return ($lines -join "`n")
    }

    if ($Value -is [System.Collections.IEnumerable]) {
        $lines = @("{")
        foreach ($item in $Value) {
            $converted = ConvertTo-LuauValue $item ($Indent + 4)
            $lines += "$childPad$converted,"
        }
        $lines += "$pad}"
        return ($lines -join "`n")
    }

    throw "Unsupported value type: $($Value.GetType().FullName)"
}

function New-OrderedNode {
    return [ordered]@{}
}

function Set-NestedContentValue {
    param(
        [System.Collections.Specialized.OrderedDictionary]$Root,
        [string[]]$Segments,
        $Value
    )

    $node = $Root
    for ($i = 0; $i -lt $Segments.Length - 1; $i++) {
        $segment = $Segments[$i]
        if (-not $node.Contains($segment)) {
            $node[$segment] = New-OrderedNode
        }
        $node = $node[$segment]
    }

    $node[$Segments[$Segments.Length - 1]] = $Value
}

$rootPath = Resolve-Path $ContentRoot
$rootFullPath = $rootPath.ProviderPath.TrimEnd([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
$files = Get-ChildItem -Path $rootPath -Recurse -Filter *.json | Sort-Object FullName

if ($files.Count -eq 0) {
    throw "No JSON files found under $ContentRoot"
}

$content = New-OrderedNode

foreach ($file in $files) {
    $fileFullPath = (Resolve-Path $file.FullName).ProviderPath
    if (-not $fileFullPath.StartsWith($rootFullPath, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "File $fileFullPath is outside content root $rootFullPath"
    }

    $relativePath = $fileFullPath.Substring($rootFullPath.Length).TrimStart([System.IO.Path]::DirectorySeparatorChar, [System.IO.Path]::AltDirectorySeparatorChar)
    $withoutExtension = $relativePath -replace "(?i)\.json$", ""
    $segments = $withoutExtension -split "[\\/]" | ForEach-Object {
        ($_ -replace "[^A-Za-z0-9_]", "_").ToLowerInvariant()
    }

    $json = Get-Content -Raw -Encoding UTF8 -Path $file.FullName
    $parsed = $json | ConvertFrom-Json
    Set-NestedContentValue -Root $content -Segments $segments -Value $parsed
}

$generatedAt = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$moduleBody = ConvertTo-LuauValue $content 0
$luau = @"
-- Generated by tools/build-content.ps1 at $generatedAt.
-- Edit files under content/ instead of editing this module directly.

return $moduleBody
"@

$outputDirectory = Split-Path -Parent $OutputPath
if ($outputDirectory) {
    New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
}

$outputFullPath = Join-Path (Get-Location) $OutputPath
$utf8WithoutBom = New-Object System.Text.UTF8Encoding -ArgumentList $false
[System.IO.File]::WriteAllText($outputFullPath, $luau, $utf8WithoutBom)
Write-Host "Generated $OutputPath from $($files.Count) JSON files."
